language: python
sudo: false

matrix:
  include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"

before_install:
  - pip install pytest pytest-cov codecov coverage

install:
  - python setup.py install

script:
  - python -m pytest tests/
  - coverage run setup.py test

after_success:
  - codecov
